#
#
# Each new term in the Fibonacci sequence is generated by
# adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.


def fib(n):
    a = 1
    b = 2
    while True:
        if a < n:
            yield a
        else:
            break
        a, b = b, a + b


sum_of_nums = 0
for i in fib(4000000):
    if i % 2 == 0:
        sum_of_nums += i

print(sum_of_nums)
